# EOS25 template

### Simulation Options ###
[SimulationOptions]
HII_DIM = 1365
DIM = 4095
BOX_LEN = 2048
N_THREADS = 48
SAMPLER_MIN_MASS = 1e9

### Astro Params ###
[AstroParams]
F_STAR10 = -1.25
F_STAR7_MINI = -2.5
F_ESC10 = -1.22
F_ESC7_MINI = -2.22
ALPHA_STAR = 0.5
ALPHA_STAR_MINI = 0.0
ALPHA_ESC = -0.3
M_TURN = 5.0
t_STAR = 0.5
L_X = 40.5
NU_X_THRESH = 500
SIGMA_STAR = 0.14
SIGMA_LX = 0.5
SIGMA_SFR_LIM = 0.19
SIGMA_SFR_INDEX = -0.12

### Matter Options ###
[MatterOptions]
USE_HALO_FIELD = true
HALO_STOCHASTICITY = true
KEEP_3D_VELOCITIES = true
MINIMIZE_MEMORY = true


### Astro Options ###
[AstroOptions]
USE_MINI_HALOS = true
USE_TS_FLUCT = true
INHOMO_RECO = true

[CosmoParams]
