# EOS25 template

### Astro Params ###
[AstroParams]
F_STAR10 = -1.25
F_STAR7_MINI = -2.5
F_ESC10 = -1.22
F_ESC7_MINI = -2.22
ALPHA_STAR = 0.5
ALPHA_STAR_MINI = 0.0
ALPHA_ESC = -0.3
M_TURN = 5.0
t_STAR = 0.5
L_X = 40.5
NU_X_THRESH = 500
SIGMA_STAR = 0.25
SIGMA_LX = 0.5
SIGMA_SFR_LIM = 0.19
SIGMA_SFR_INDEX = -0.12

HII_EFF_FACTOR = 30.0
R_BUBBLE_MAX = 15.0
R_BUBBLE_MIN = 0.620350491
ION_Tvir_MIN = 4.69897
X_RAY_SPEC_INDEX = 1.0
X_RAY_Tvir_MIN = 4.69897
F_H2_SHIELD = 0.0
N_RSD_STEPS = 20
A_LW = 2.0
BETA_LW = 0.6
A_VCB = 1.0
BETA_VCB = 1.8
UPPER_STELLAR_TURNOVER_MASS = 11.447
UPPER_STELLAR_TURNOVER_INDEX = -0.6
T_RE = 2e4
FIXED_VAVG = 25.86
POP2_ION = 5000.0
POP3_ION = 44021.0
PHOTONCONS_CALIBRATION_END = 3.5
CLUMPING_FACTOR = 2.0
ALPHA_UVB = 5.0
R_MAX_TS = 500.0
N_STEP_TS = 40
MAX_DVDR = 0.2
DELTA_R_HII_FACTOR = 1.1
NU_X_BAND_MAX = 2000.0
NU_X_MAX = 10000.0

### Cosmo Params ###
[CosmoParams]
SIGMA_8 = 0.8102
hlittle = 0.6766
OMm = 0.30966
OMb = 0.04897
POWER_INDEX = 0.9665
OMn = 0.0
OMk = 0.0
OMr = 8.6e-5
OMtot = 1.0
Y_He = 0.24
wl = -1.0 

### Simulation Options ###
[SimulationOptions]
HII_DIM = 1365
DIM = 4095
BOX_LEN = 2048
N_THREADS = 25
SAMPLER_MIN_MASS = 1e9

NON_CUBIC_FACTOR = 1.0
SAMPLER_BUFFER_FACTOR = 2.0
N_COND_INTERP = 200
N_PROB_INTERP = 400
MIN_LOGPROB = -12
HALOMASS_CORRECTION = 0.89
PARKINSON_G0 = 1.0
PARKINSON_y1 = 0.0
PARKINSON_y2 = 0.0
Z_HEAT_MAX = 35.0
ZPRIME_STEP_FACTOR = 1.02
INITIAL_REDSHIFT = 300.0
DELTA_R_FACTOR = 1.1
DENSITY_SMOOTH_RADIUS = 0.2
DEXM_OPTIMIZE_MINMASS = 1e11
DEXM_R_OVERLAP = 2
CORR_STAR = 0.5
CORR_SFR = 0.2
CORR_LX = 0.2

### Matter Options ###
[MatterOptions]
USE_HALO_FIELD = true
HALO_STOCHASTICITY = true
KEEP_3D_VELOCITIES = true
MINIMIZE_MEMORY = true

HMF = "ST"
USE_RELATIVE_VELOCITIES = false
POWER_SPECTRUM = "EH" 
PERTURB_ON_HIGH_RES = false
USE_INTERPOLATION_TABLES = "hmf-interpolation"
SAMPLE_METHOD = "MASS-LIMITED"
FILTER = "spherical-tophat"
HALO_FILTER = "spherical-tophat"
SMOOTH_EVOLVED_DENSITY_FIELD = false
DEXM_OPTIMIZE = false
PERTURB_ALGORITHM = "2LPT"
USE_FFTW_WISDOM = false
FIXED_HALO_GRIDS = false


### Astro Options ###
[AstroOptions]
USE_MINI_HALOS = false
USE_TS_FLUCT = true
INHOMO_RECO = true

USE_CMB_HEATING = true
USE_LYA_HEATING = true
USE_MASS_DEPENDENT_ZETA = true
APPLY_RSDS = true
SUBCELL_RSD = false
FIX_VCB_AVG = false
USE_EXP_FILTER = true
CELL_RECOMB = true
PHOTON_CONS_TYPE = "no-photoncons"
USE_UPPER_STELLAR_TURNOVER = true
M_MIN_in_Mass = true
HALO_SCALING_RELATIONS_MEDIAN = false
HII_FILTER = "spherical-tophat"
HEAT_FILTER = "spherical-tophat"
IONISE_ENTIRE_SPHERE = false
AVG_BELOW_SAMPLER = true
INTEGRATION_METHOD_ATOMIC = "GAUSS-LEGENDRE"
INTEGRATION_METHOD_MINI = "GAUSS-LEGENDRE"
